version: '3.4'

services:
  foodapi:
    image: ${DOCKER_REGISTRY-}foodapi
    ports:
        - 5001:80
    build:
      context: .
      dockerfile: FoodAPI/Dockerfile

  beverageapi:
    image: ${DOCKER_REGISTRY-}beverageapi
    ports:
        - 5002:80
    build:
      context: .
      dockerfile: BeverageAPI/Dockerfile

  envoygateway:
    build: Envoy/
    ports:
        - "9901:9901"
        - "10000:10000"
    volumes:
        - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
