version: '3.4'

services:
  foodapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  beverageapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

