version: '3.4'

    

services:
  sensorservice:
    image: ${DOCKER_REGISTRY-}sensorservice
    build:
      context: .
      dockerfile: SensorService/Dockerfile
    ports:
      - 5001:80

  dataservice:
    image: ${DOCKER_REGISTRY-}dataservice
    build:
      context: .
      dockerfile: DataService/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - mongo
      - rabbitmq

  analystservice:
    image: ${DOCKER_REGISTRY-}analystservice
    ports:
      - 5002:80
    build:
      context: .
      dockerfile: AnalystService/Dockerfile
    depends_on:
      - rabbitmq


  commandservice:
    image: ${DOCKER_REGISTRY-}commandservice
    ports:
      - 5003:80
    build:
      context: .
      dockerfile: CommandService/Dockerfile
    depends_on:
      - rabbitmq

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"

volumes:
  mongodata:

